# Setup
title:        Pacific
tagline:      Distributed stock investments
baseurl:      "/pacific"
paginate:     1

# About/contact
author:
  name:       axsavage
  url:        http://axsavage.github.io/pacific

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
